// Third-party libraries and data used by Cog and XPCog.
//
// Compiled 2026-10-01 from the licence files in both source trees: Cog at
// ~/Projects/Cog (Frameworks/, ThirdParty/, Plugins/, submodules, the prebuilt
// ThirdParty/libraries.tar.xz) and XPCog at ~/Projects/XPCog (vendor/, ports/,
// vcpkg's share/<port>/copyright, the system licence files, and its own
// audited table in uicore/src/Credits.cpp). `source` says where each licence
// was read. "unknown" means neither tree carries a licence statement for it;
// the page credits those by name and use only, with no licence line.
//
// Left out on purpose: Cog's own code and data (its plugins, Cog.q1.json), and
// components in Cog's tree that no Cog project builds (DUMB, modplay,
// playptmod, munt, midi_processing, lazyusf v1, BASS/BASSMODS).

export type Group = "decoders" | "processing" | "interface" | "data";
export type App = "cog" | "xpcog";

export interface Credit {
  name: string;
  url: string;
  license: string;
  licenseUrl?: string;
  copyright?: string;
  use: string;
  usedBy: App[];
  group: Group;
  source?: string;
}

export const credits: Credit[] = [
  // ---------------------------------------------------------------- decoders
  { name: "FFmpeg", url: "https://ffmpeg.org", license: "LGPL-2.1-or-later", use: "Decodes AAC, ALAC, WMA, AC-3, DTS and most container formats", usedBy: ["cog", "xpcog"], group: "decoders", source: "Cog: ThirdParty/ffmpeg/include/libavcodec/avcodec.h; XPCog: Credits.cpp" },
  { name: "libFLAC", url: "https://xiph.org/flac/", license: "BSD-3-Clause", copyright: "© 2000–2009 Josh Coalson; © 2011–2025 Xiph.Org Foundation", use: "Decodes FLAC", usedBy: ["cog", "xpcog"], group: "decoders", source: "Cog: ThirdParty/flac/include/FLAC/format.h; XPCog: vcpkg share/libflac/copyright" },
  { name: "libogg", url: "https://xiph.org/ogg/", license: "BSD-3-Clause", copyright: "© 2002 Xiph.Org Foundation", use: "Reads the Ogg container", usedBy: ["cog", "xpcog"], group: "decoders", source: "XPCog: vcpkg share/libogg/copyright; Cog: ThirdParty/ogg/include/ogg/ogg.h" },
  { name: "libvorbis", url: "https://xiph.org/vorbis/", license: "BSD-3-Clause", copyright: "© 2002–2020 Xiph.Org Foundation", use: "Decodes Ogg Vorbis", usedBy: ["cog", "xpcog"], group: "decoders", source: "XPCog: vcpkg share/libvorbis/copyright; Cog: ThirdParty/vorbis/include/vorbis/codec.h" },
  { name: "Opus", url: "https://opus-codec.org", license: "BSD-3-Clause", copyright: "© 2001–2023 Xiph.Org, Skype Limited, Octasic and contributors", use: "Decodes Opus", usedBy: ["cog", "xpcog"], group: "decoders", source: "XPCog: /usr/share/licenses/opus/COPYING; Cog: ThirdParty/opus/include/opus.h" },
  { name: "opusfile", url: "https://opus-codec.org", license: "BSD-3-Clause", copyright: "© 1994–2013 Xiph.Org Foundation and contributors", use: "Reads Opus files", usedBy: ["cog", "xpcog"], group: "decoders", source: "XPCog: /usr/share/licenses/opusfile; Cog: ThirdParty/opusfile/include/opusfile.h" },
  { name: "minimp3", url: "https://github.com/lieff/minimp3", license: "CC0-1.0", use: "Decodes MP3", usedBy: ["cog", "xpcog"], group: "decoders", source: "Cog: Plugins/minimp3/ThirdParty/minimp3.h; XPCog: vendor/minimp3" },
  { name: "mpg123", url: "https://mpg123.org", license: "LGPL-2.1-only", copyright: "© 1995–2020 Michael Hipp and others", use: "Decodes MP3 samples inside tracker modules and game streams", usedBy: ["cog", "xpcog"], group: "decoders", source: "Cog: ThirdParty/mpg123/include/mpg123/mpg123.h; XPCog: vcpkg share/mpg123/copyright" },
  { name: "WavPack", url: "https://www.wavpack.com", license: "BSD-3-Clause", copyright: "© 1998–2025 David Bryant", use: "Decodes WavPack", usedBy: ["cog", "xpcog"], group: "decoders", source: "XPCog: /usr/share/licenses/wavpack; Cog: ThirdParty/WavPack/include/wavpack.h" },
  { name: "Musepack decoder (libmpcdec)", url: "https://www.musepack.net", license: "BSD-3-Clause", copyright: "© 2005 The Musepack Development Team", use: "Decodes Musepack", usedBy: ["cog", "xpcog"], group: "decoders", source: "Cog: Frameworks/MPCDec/Files/COPYING; XPCog: /usr/share/licenses/libmpcdec" },
  { name: "TagLib", url: "https://taglib.org", license: "LGPL-2.1-only OR MPL-1.1", use: "Reads tags", usedBy: ["cog", "xpcog"], group: "decoders", source: "Cog: ThirdParty/Frameworks/tag.framework/.../tag.h; XPCog: Credits.cpp" },
  { name: "UTF8-CPP", url: "https://github.com/nemtrif/utfcpp", license: "BSL-1.0", use: "Converts text for TagLib", usedBy: ["xpcog"], group: "decoders", source: "XPCog: upstream LICENSE (vcpkg dependency of taglib)" },
  { name: "libopenmpt", url: "https://lib.openmpt.org", license: "BSD-3-Clause", copyright: "© 2004–2026 OpenMPT Project Developers and Contributors; © 1997–2003 Olivier Lapicque", use: "Plays tracker modules (MOD, S3M, XM, IT and more)", usedBy: ["cog", "xpcog"], group: "decoders", source: "Cog: Frameworks/OpenMPT/OpenMPT/LICENSE; XPCog: /usr/share/licenses/libopenmpt" },
  { name: "Game Music Emu", url: "https://github.com/libgme/game-music-emu", license: "LGPL-2.1-or-later", use: "Plays console chiptunes (NSF, SPC, GBS, VGM and more)", usedBy: ["cog", "xpcog"], group: "decoders", source: "Cog: Frameworks/GME/license.txt" },
  { name: "emu2413", url: "https://github.com/digital-sound-antiques/emu2413", license: "MIT", copyright: "© Mitsutaka Okazaki", use: "Emulates the YM2413 for Game Music Emu", usedBy: ["cog"], group: "decoders", source: "Cog: Frameworks/GME/gme/ext/LICENSE" },
  { name: "vgmstream", url: "https://github.com/vgmstream/vgmstream", license: "ISC", copyright: "© 2008–2025 Adam Gashlin, Fastelbja, Ronny Elfert, bnnm and others", use: "Plays several hundred game audio stream formats", usedBy: ["cog", "xpcog"], group: "decoders", source: "XPCog: vcpkg share/vgmstream/copyright (Cog's tree has no top-level licence)" },
  { name: "LibAtrac9", url: "https://github.com/Thealexbarney/LibAtrac9", license: "MIT", copyright: "© Alex Barney", use: "Decodes ATRAC9 for vgmstream", usedBy: ["cog"], group: "decoders", source: "Cog: Frameworks/libatrac9/libatrac9/LICENSE" },
  { name: "CELT 0.6.1 and 0.11.0", url: "https://gitlab.xiph.org/xiph/celt", license: "BSD-3-Clause", copyright: "© Jean-Marc Valin, Timothy B. Terriberry, CSIRO", use: "Decodes FSB CELT for vgmstream", usedBy: ["cog"], group: "decoders", source: "Cog: Frameworks/libcelt_0061/celt-0.6.1/COPYING, libcelt_0110/celt-0.11.0/COPYING" },
  { name: "Speex", url: "https://www.speex.org", license: "BSD-3-Clause", copyright: "© Jean-Marc Valin", use: "Decodes Speex for vgmstream", usedBy: ["cog"], group: "decoders", source: "Cog: ThirdParty/speex/include/speex/speex.h" },
  { name: "Fraunhofer FDK AAC", url: "https://sourceforge.net/projects/opencore-amr/", license: "FDK AAC licence", use: "Decodes AAC for FFmpeg and vgmstream", usedBy: ["cog"], group: "decoders", source: "Cog: ThirdParty/fdk-aac/include/fdk-aac/aacdecoder_lib.h (Software License for The Fraunhofer FDK AAC Codec Library for Android)" },
  { name: "G.719 reference code", url: "", license: "unknown", use: "Decodes G.719 for vgmstream", usedBy: ["cog"], group: "decoders", source: "Cog: Frameworks/g719/g719/reference_code/common/bitalloc.c says '© 2008 Ericsson AB. and Polycom Inc. All rights reserved', no terms" },
  { name: "libsidplayfp", url: "https://github.com/libsidplayfp/libsidplayfp", license: "GPL-2.0-or-later", use: "Plays Commodore 64 SID tunes", usedBy: ["cog", "xpcog"], group: "decoders", source: "Cog: Frameworks/libsidplayfp/sidplayfp/COPYING; XPCog: ports/libsidplayfp" },
  { name: "AdPlug", url: "https://adplug.github.io", license: "LGPL-2.1-or-later", use: "Plays AdLib and OPL2 music", usedBy: ["cog", "xpcog"], group: "decoders", source: "Cog: Frameworks/AdPlug/AdPlug/adplug/COPYING; XPCog: ports/adplug" },
  { name: "libbinio", url: "https://github.com/adplug/libbinio", license: "LGPL-2.1-or-later", use: "Reads files for AdPlug", usedBy: ["cog", "xpcog"], group: "decoders", source: "Cog: Frameworks/libbinio/libbinio/libbinio/COPYING; XPCog: ports/libbinio" },
  { name: "libvgm", url: "https://github.com/ValleyBell/libvgm", license: "unknown", use: "Plays VGM, S98, DRO and GYM chip logs", usedBy: ["cog", "xpcog"], group: "decoders", source: "Neither tree states it: Cog ThirdParty/libvgm/README.md has no licence, XPCog's vcpkg share/libvgm/copyright has none; XPCog's About says GPL-2.0, unverified" },
  { name: "mGBA", url: "https://mgba.io", license: "MPL-2.0", use: "Plays GSF (Game Boy Advance) rips", usedBy: ["cog", "xpcog"], group: "decoders", source: "Cog: Frameworks/mGBA/mGBA/mgba/LICENSE; XPCog: ports/mgba" },
  { name: "inih", url: "https://github.com/benhoyt/inih", license: "BSD-3-Clause", copyright: "© Ben Hoyt", use: "Parses INI files inside mGBA", usedBy: ["cog"], group: "decoders", source: "Cog: Frameworks/mGBA/mGBA/mgba/src/third-party/inih/LICENSE.txt ('New BSD license')" },
  { name: "VBA-M", url: "https://github.com/visualboyadvance-m/visualboyadvance-m", license: "GPL-2.0-or-later", use: "Emulates the Game Boy Advance for HighlyComplete", usedBy: ["cog"], group: "decoders", source: "Cog: Frameworks/HighlyAdvanced/HighlyAdvanced/vbam/License.txt" },
  { name: "HighlyExperimental", url: "", license: "unknown", use: "Emulates the PlayStation for PSF and PSF2", usedBy: ["cog", "xpcog"], group: "decoders", source: "No licence text in Cog's Frameworks/HighlyExperimental or XPCog's vendor/highlyexperimental" },
  { name: "HighlyQuixotic", url: "", license: "unknown", use: "Emulates Capcom QSound for QSF", usedBy: ["cog", "xpcog"], group: "decoders", source: "No licence text in either tree; Cog's Readme says its Z80 core is MAME-based (z80.c © 1997–1999 Neill Corlett)" },
  { name: "HighlyTheoretical", url: "", license: "GPL-3.0", use: "Emulates the Sega Saturn and Dreamcast for SSF and DSF", usedBy: ["cog", "xpcog"], group: "decoders", source: "Core/COPYING.txt is the GPL v3 text in both trees; it does not say whether later versions apply" },
  { name: "C68K", url: "", license: "GPL-2.0-or-later", copyright: "© Stéphane Dallongeville", use: "Emulates the 68000 for HighlyTheoretical", usedBy: ["cog"], group: "decoders", source: "Cog: Frameworks/HighlyTheoretical/HighlyTheoretical/Core/c68k/c68k.c" },
  { name: "Musashi", url: "https://github.com/kstenerud/Musashi", license: "Musashi licence (free for non-commercial use)", copyright: "© Karl Stenerud", use: "Emulates the 68000 for HighlyTheoretical", usedBy: ["cog", "xpcog"], group: "decoders", source: "Cog: Frameworks/HighlyTheoretical/HighlyTheoretical/Core/m68k/readme.txt" },
  { name: "lazyusf2", url: "https://bitbucket.org/kode54/lazyusf2", license: "GPL-2.0-or-later", use: "Emulates the Nintendo 64 for USF", usedBy: ["cog", "xpcog"], group: "decoders", source: "Cog: Frameworks/lazyusf2/lazyusf2/r4300/r4300.c; XPCog: vendor/lazyusf2 headers" },
  { name: "Snes9x", url: "https://www.snes9x.com", license: "Snes9x licence (non-commercial)", copyright: "© 1996–2002 Gary Henderson and the Snes9x team", use: "Emulates the Super Nintendo for SNSF", usedBy: ["cog", "xpcog"], group: "decoders", source: "Cog: Frameworks/snes9x/snes9x/LICENSE; XPCog: vendor/snes9x/LICENSE" },
  { name: "Snes9x APU", url: "https://www.snes9x.com", license: "LGPL-2.1", use: "Emulates the SNES sound processor", usedBy: ["cog", "xpcog"], group: "decoders", source: "Cog: Frameworks/snes9x/snes9x/src/apu/license.txt" },
  { name: "melonDS", url: "https://melonds.kuribo64.net", license: "GPL-3.0-or-later", copyright: "© 2016–2026 melonDS team", use: "Emulates the Nintendo DS for 2SF", usedBy: ["cog", "xpcog"], group: "decoders", source: "Both trees: vio2sf melonDS headers ('version 3 … or any later version')" },
  { name: "Teakra", url: "https://github.com/wwylele/teakra", license: "MIT", use: "Emulates the DSi DSP inside melonDS", usedBy: ["cog"], group: "decoders", source: "Cog: Frameworks/vio2sf/.../teakra/teakra_LICENSE" },
  { name: "Dolphin", url: "https://dolphin-emu.org", license: "GPL-2.0-or-later", use: "Provides JIT helpers inside melonDS", usedBy: ["cog", "xpcog"], group: "decoders", source: "Both trees: vio2sf dolphin/license_dolphin.txt and 'Licensed under GPLv2+' headers" },
  { name: "FatFs", url: "http://elm-chan.org/fsw/ff/", license: "FatFs licence (BSD-style)", copyright: "© 2021 ChaN", use: "Provides a FAT file system inside melonDS", usedBy: ["cog", "xpcog"], group: "decoders", source: "Both trees: vio2sf fatfs/ff.c and fatfs_LICENSE.txt" },
  { name: "tiny-AES-c", url: "https://github.com/kokke/tiny-AES-c", license: "Unlicense", use: "Provides AES inside melonDS", usedBy: ["cog", "xpcog"], group: "decoders", source: "Both trees: vio2sf tiny-AES-c/tiny-AES-c-unlicense.txt" },
  { name: "xxHash", url: "https://github.com/Cyan4973/xxHash", license: "BSD-2-Clause", copyright: "© 2012–2023 Yann Collet", use: "Provides hashing inside melonDS", usedBy: ["xpcog"], group: "decoders", source: "XPCog: vendor/vio2sf/src/xxhash/xxhash.h" },
  { name: "SHA-1 (Steve Reid)", url: "", license: "public domain", copyright: "By Steve Reid", use: "Provides SHA-1 inside melonDS", usedBy: ["xpcog"], group: "decoders", source: "XPCog: vendor/vio2sf/src/sha1/sha1.c ('100% Public Domain')" },
  { name: "blip_buf", url: "http://www.slack.net/~ant/", license: "LGPL-2.1-or-later", copyright: "© 2003–2009 Shay Green", use: "Band-limited synthesis for the Hively replayer and melonDS", usedBy: ["cog", "xpcog"], group: "decoders", source: "Both trees: blip_buf.c headers (HivelyPlayer, vio2sf)" },
  { name: "psflib", url: "", license: "unknown", use: "Reads the PSF container", usedBy: ["cog", "xpcog"], group: "decoders", source: "No licence text in Cog's Frameworks/psflib or XPCog's vendor/psflib" },
  { name: "SSEQPlayer", url: "https://github.com/fincs/FSS", license: "unknown", copyright: "Naram Qashat (CyberBotX)", use: "Plays NCSF (Nintendo DS SSEQ)", usedBy: ["cog", "xpcog"], group: "decoders", source: "No licence text in either tree; attribution only: Naram Qashat (CyberBotX), after fincs' FSS" },
  { name: "Hively replayer", url: "", license: "unknown", use: "Plays AHX and HivelyTracker modules", usedBy: ["cog", "xpcog"], group: "decoders", source: "No licence text in Cog's HivelyPlayer/hvl_replay.c or XPCog's vendor/hively" },
  { name: "Syntrax (libjaytrax)", url: "https://bitbucket.org/rhinoid/", license: "GPL-3.0-only", copyright: "© Reinier van Vliet; © Christopher Snowhill", use: "Plays Syntrax modules", usedBy: ["cog", "xpcog"], group: "decoders", source: "Cog: Frameworks/Syntrax-c/Syntrax-c/jaytrax.c (SPDX)" },
  { name: "Organya player", url: "http://iki.fi/bisqwit/", license: "unknown", copyright: "Joel Yliluoma", use: "Plays Cave Story's Organya music", usedBy: ["cog", "xpcog"], group: "decoders", source: "Cog: Plugins/Organya/OrganyaDecoder.mm; attribution only, no licence" },
  { name: "SpessaSynth Core", url: "https://github.com/spessasus/spessasynth_core", license: "Apache-2.0", use: "Synthesises MIDI with SoundFonts", usedBy: ["cog", "xpcog"], group: "decoders", source: "Cog: Plugins/MIDI/MIDI/spessasynth_core/LICENSE; XPCog: ports/spessasynth-core" },
  { name: "Nuked OPL3", url: "https://github.com/nukeykt/Nuked-OPL3", license: "GPL-2.0-or-later", copyright: "© 2013–2016 Alexey Khokholov (Nuke.YKT)", use: "Emulates the OPL3 for MIDI playback", usedBy: ["cog", "xpcog"], group: "decoders", source: "Both trees: fmopl3lib/opl3.cpp" },
  { name: "Chocolate Doom OPL music", url: "https://www.chocolate-doom.org", license: "GPL-2.0-or-later", copyright: "© 1993–1996 Id Software, Inc.; © 2005–2014 Simon Howard", use: "Drives the OPL3 for MIDI playback", usedBy: ["cog", "xpcog"], group: "decoders", source: "Both trees: synthlib_doom/i_oplmusic.cpp" },
  { name: "Nuked SC-55", url: "https://github.com/nukeykt/Nuked-SC55", license: "MAME licence (non-commercial)", copyright: "© 2021, 2024 nukeykt", use: "Emulates the Roland SC-55", usedBy: ["cog", "xpcog"], group: "decoders", source: "Cog: Frameworks/nuked-sc55/LICENSE; XPCog: vendor/nuked-sc55 headers" },
  { name: "stb_vorbis", url: "https://github.com/nothings/stb", license: "MIT OR Unlicense", copyright: "© Sean Barrett", use: "Decodes Ogg-compressed SoundFont samples", usedBy: ["cog"], group: "decoders", source: "Cog: Plugins/MIDI/MIDI/stb_vorbis/stb_vorbis.h" },
  { name: "Shorten", url: "", license: "GPL-2.0 plus the Shorten licence (not to be sold without SoftSound's permission)", use: "Decodes Shorten (.shn)", usedBy: ["cog"], group: "decoders", source: "Cog: Frameworks/Shorten/Files/COPYING, shorten/doc/LICENSE.shorten" },
  { name: "File_Extractor", url: "http://www.slack.net/~ant/", license: "LGPL-2.1-or-later", copyright: "© Shay Green", use: "Plays music straight out of archives", usedBy: ["cog"], group: "decoders", source: "Cog: Frameworks/File_Extractor/File_Extractor/fex/Data_Reader.cpp" },
  { name: "LZMA SDK (7z_C)", url: "https://www.7-zip.org/sdk.html", license: "public domain", use: "Extracts 7-Zip archives", usedBy: ["cog"], group: "decoders", source: "Cog: Frameworks/File_Extractor/File_Extractor/7z_C/ headers" },
  { name: "UnRAR", url: "https://www.rarlab.com", license: "UnRAR licence (freeware; may not be used to re-create RAR compression)", use: "Extracts RAR archives", usedBy: ["cog"], group: "decoders", source: "Cog: Frameworks/File_Extractor/File_Extractor/unrar/license.txt" },
  { name: "libarchive", url: "https://www.libarchive.org", license: "BSD-2-Clause", copyright: "© 2003–2010 Tim Kientzle", use: "Plays music straight out of archives", usedBy: ["xpcog"], group: "decoders", source: "XPCog: /usr/include/archive.h, /usr/share/licenses/libarchive" },
  { name: "bzip2", url: "https://sourceware.org/bzip2/", license: "bzip2-1.0.6", copyright: "© 1996–2019 Julian R Seward", use: "Decompresses bzip2 archives for libarchive", usedBy: ["xpcog"], group: "decoders", source: "XPCog: /usr/share/licenses/bzip2/LICENSE" },
  { name: "XZ Utils (liblzma)", url: "https://tukaani.org/xz/", license: "0BSD", use: "Decompresses XZ and LZMA archives for libarchive", usedBy: ["xpcog"], group: "decoders", source: "XPCog: /usr/share/licenses/xz/COPYING" },
  { name: "LZ4", url: "https://lz4.org", license: "BSD-2-Clause", copyright: "© 2011–2020 Yann Collet", use: "Decompresses LZ4 archives for libarchive", usedBy: ["xpcog"], group: "decoders", source: "XPCog: upstream lib/LICENSE" },
  { name: "Zstandard", url: "https://facebook.github.io/zstd/", license: "BSD-3-Clause", copyright: "© Meta Platforms, Inc. and affiliates", use: "Decompresses Zstandard archives for libarchive", usedBy: ["xpcog"], group: "decoders", source: "XPCog: /usr/share/licenses/zstd/LICENSE" },
  { name: "libid3tag", url: "https://codeberg.org/tenacityteam/libid3tag", license: "GPL-2.0-or-later", copyright: "© Underbit Technologies", use: "Reads ID3 tags for the MP3 decoder", usedBy: ["cog"], group: "decoders", source: "Cog: ThirdParty/libid3tag/include/id3tag.h" },
  { name: "vorbis-tools picture code", url: "https://xiph.org", license: "GPL-2.0-or-later", use: "Reads Vorbis cover art", usedBy: ["cog"], group: "decoders", source: "Cog: Plugins/Vorbis/vorbis-tools/share/picture.c, base64.c" },
  { name: "SFBAudioEngine Core Audio decoder", url: "https://github.com/sbooth/SFBAudioEngine", license: "GPL-2.0-or-later", copyright: "© Stephen F. Booth", use: "Decodes through Core Audio", usedBy: ["cog"], group: "decoders", source: "Cog: Plugins/CoreAudio/CoreAudioDecoder.m" },
  { name: "CVbriHeader", url: "", license: "unknown", use: "Reads VBRI headers in MP3 files", usedBy: ["cog"], group: "decoders", source: "Cog: Plugins/minimp3/ThirdParty/CVbriHeader.c says '(C) copyright Fraunhofer - IIS (2000) All Rights Reserved', no terms" },

  // -------------------------------------------------------------- processing
  { name: "Rubber Band Library", url: "https://breakfastquay.com/rubberband/", license: "GPL-2.0-or-later", use: "Changes pitch and tempo independently", usedBy: ["cog", "xpcog"], group: "processing", source: "Cog: ThirdParty/rubberband/include/rubberband/RubberBandStretcher.h, Base.lproj/Credits.html" },
  { name: "Signalsmith Stretch", url: "https://github.com/Signalsmith-Audio/signalsmith-stretch", license: "MIT", copyright: "© 2022 Geraint Luff / Signalsmith Audio Ltd.", use: "Changes pitch and tempo independently", usedBy: ["cog", "xpcog"], group: "processing", source: "Cog: ThirdParty/signalsmith/signalsmith-stretch/LICENSE.txt; XPCog: vendor/signalsmith/LICENSE-stretch.txt" },
  { name: "Signalsmith Linear", url: "https://github.com/Signalsmith-Audio/linear", license: "MIT", copyright: "© 2025 Signalsmith Audio", use: "Provides the FFT under Signalsmith Stretch", usedBy: ["cog", "xpcog"], group: "processing", source: "Cog: ThirdParty/signalsmith/signalsmith-linear/LICENSE.txt; XPCog: vendor/signalsmith/LICENSE-linear.txt" },
  { name: "SoX Resampler (libsoxr)", url: "https://sourceforge.net/projects/soxr/", license: "LGPL-2.1-or-later", copyright: "© 2007–2018 robs@users.sourceforge.net", use: "Converts sample rates", usedBy: ["cog", "xpcog"], group: "processing", source: "Cog: ThirdParty/soxr/include/soxr.h; XPCog: /usr/share/licenses/libsoxr" },
  { name: "libsamplerate", url: "https://libsndfile.github.io/libsamplerate/", license: "BSD-2-Clause", copyright: "© 2012–2016 Erik de Castro Lopo", use: "Resamples for Rubber Band", usedBy: ["xpcog"], group: "processing", source: "XPCog: /usr/share/licenses/libsamplerate/COPYING" },
  { name: "SLEEF", url: "https://sleef.org", license: "BSL-1.0", use: "Vector maths for Rubber Band", usedBy: ["xpcog"], group: "processing", source: "XPCog: upstream LICENSE.txt (vcpkg dependency of rubberband)" },
  { name: "FreeSurround", url: "", license: "GPL-2.0-or-later", copyright: "© 2007–2010 Christian Kothe", use: "Upmixes stereo to surround", usedBy: ["cog", "xpcog"], group: "processing", source: "Cog: Audio/ThirdParty/fsurround/freesurround_decoder.cpp; XPCog: vendor/fsurround" },
  { name: "HDCD decoder (hdcd_decode2)", url: "", license: "BSD-3-Clause", copyright: "© 2010–2023 Christopher Snowhill", use: "Decodes HDCD", usedBy: ["cog", "xpcog"], group: "processing", source: "Both trees: hdcd_decode2.c (three clauses)" },
  { name: "LPC extrapolation (lvqcl)", url: "", license: "ISC", copyright: "© 2013, 2018 lvqcl", use: "Extrapolates gapless edges", usedBy: ["cog", "xpcog"], group: "processing", source: "Cog: Audio/ThirdParty/lvqcl/lpc.c; XPCog: vendor/lpc" },
  { name: "dsd2pcm", url: "", license: "BSD", copyright: "Sebastian Gesemann", use: "Converts DSD to PCM", usedBy: ["xpcog"], group: "processing", source: "XPCog: vendor/dsd2pcm (Credits.cpp; clause count not re-read)" },
  { name: "miniaudio", url: "https://miniaud.io", license: "Unlicense OR MIT-0", copyright: "David Reid", use: "Plays audio to the output device", usedBy: ["xpcog"], group: "processing", source: "XPCog: vendor/miniaudio/miniaudio.h" },
  { name: "DeaDBeeF FFT", url: "https://deadbeef.sourceforge.io", license: "Zlib", copyright: "© Alexey Yakovenko", use: "Provides the spectrum analyser's FFT", usedBy: ["cog"], group: "processing", source: "Cog: Audio/ThirdParty/deadbeef/fft.h" },
  { name: "SFBAudioEngine Core Audio utilities", url: "https://github.com/sbooth/SFBAudioEngine", license: "GPL-2.0-or-later", copyright: "© Stephen F. Booth", use: "Helpers for Core Audio", usedBy: ["cog"], group: "processing", source: "Cog: Audio/ThirdParty/CoreAudioUtils/CoreAudioUtils.m" },
  { name: "HRTF (MinPHR) loader", url: "", license: "unknown", use: "Loads HRTF data for headphone virtualisation", usedBy: ["cog"], group: "processing", source: "Cog: Audio/ThirdParty/hrtf/HrtfData.cpp, no licence" },

  // --------------------------------------------------------------- interface
  { name: "wxWidgets", url: "https://www.wxwidgets.org", license: "LGPL-2.0-or-later WITH WxWindows-exception-3.1", use: "Draws XPCog's interface on Windows", usedBy: ["xpcog"], group: "interface", source: "XPCog: Credits.cpp; vcpkg licence listing" },
  { name: "GTK", url: "https://www.gtk.org", license: "LGPL-2.1-or-later", use: "Draws XPCog's interface on Linux", usedBy: ["xpcog"], group: "interface", source: "XPCog: Credits.cpp" },
  { name: "libadwaita", url: "https://gnome.pages.gitlab.gnome.org/libadwaita/", license: "LGPL-2.1-or-later", use: "Draws XPCog's interface on Linux", usedBy: ["xpcog"], group: "interface", source: "XPCog: Credits.cpp" },
  { name: "GLib", url: "https://docs.gtk.org/glib/", license: "LGPL-2.1-or-later", use: "D-Bus, media keys and notifications on Linux", usedBy: ["xpcog"], group: "interface", source: "XPCog: Credits.cpp" },
  { name: "libsecret", url: "https://gnome.pages.gitlab.gnome.org/libsecret/", license: "LGPL-2.1-or-later", use: "Keeps passwords in the system keyring on Linux", usedBy: ["xpcog"], group: "interface", source: "XPCog: Credits.cpp" },
  { name: "NanoSVG", url: "https://github.com/memononen/nanosvg", license: "Zlib", copyright: "© Mikko Mononen", use: "Draws XPCog's interface icons on Windows", usedBy: ["xpcog"], group: "interface", source: "XPCog: Credits.cpp" },
  { name: "Lucide", url: "https://lucide.dev", license: "ISC", copyright: "© Lucide Contributors", use: "XPCog's interface icons on Windows", usedBy: ["xpcog"], group: "interface", source: "XPCog: Credits.cpp" },
  { name: "Expat", url: "https://libexpat.github.io", license: "MIT", copyright: "© 1998–2000 Thai Open Source Software Center Ltd and Clark Cooper", use: "Parses XML for wxWidgets", usedBy: ["xpcog"], group: "interface", source: "XPCog: /usr/share/licenses/expat/COPYING" },
  { name: "PCRE2", url: "https://www.pcre.org", license: "BSD-3-Clause WITH PCRE2-exception", use: "Regular expressions for wxWidgets", usedBy: ["xpcog"], group: "interface", source: "XPCog: upstream LICENCE.md" },
  { name: "libpng", url: "http://www.libpng.org", license: "libpng-2.0", use: "Loads PNG images for wxWidgets", usedBy: ["xpcog"], group: "interface", source: "XPCog: /usr/share/licenses/libpng/LICENSE" },
  { name: "libjpeg-turbo", url: "https://libjpeg-turbo.org", license: "IJG AND BSD-3-Clause AND Zlib", use: "Loads JPEG images for wxWidgets", usedBy: ["xpcog"], group: "interface", source: "XPCog: /usr/share/licenses/libjpeg-turbo/LICENSE.md" },
  { name: "libwebp", url: "https://developers.google.com/speed/webp", license: "BSD-3-Clause", copyright: "© 2010 Google Inc.", use: "Loads WebP images for wxWidgets", usedBy: ["xpcog"], group: "interface", source: "XPCog: /usr/share/licenses/libwebp/COPYING" },
  { name: "LibTIFF", url: "https://libtiff.gitlab.io/libtiff/", license: "libtiff", copyright: "© 1988–1997 Sam Leffler; © 1991–1997 Silicon Graphics, Inc.", use: "Loads TIFF images for wxWidgets", usedBy: ["xpcog"], group: "interface", source: "XPCog: /usr/share/licenses/libtiff/LICENSE.md" },
  { name: "dirent for Windows", url: "https://github.com/tronkko/dirent", license: "MIT", copyright: "© 1998–2019 Toni Ronkko", use: "Lists folders for the PSF cores on Windows", usedBy: ["xpcog"], group: "interface", source: "XPCog: upstream LICENSE" },
  { name: "SQLite", url: "https://sqlite.org", license: "Public domain", use: "Stores the music library", usedBy: ["xpcog"], group: "interface", source: "XPCog: /usr/share/licenses/sqlite (SPDX 'blessing')" },
  { name: "libcurl", url: "https://curl.se", license: "curl", copyright: "© 1996–2026 Daniel Stenberg and many contributors", use: "Fetches HTTP and internet radio", usedBy: ["xpcog"], group: "interface", source: "XPCog: vcpkg share/curl/copyright" },
  { name: "OpenSSL", url: "https://www.openssl.org", license: "Apache-2.0", use: "Secures HTTPS for libcurl", usedBy: ["xpcog"], group: "interface", source: "XPCog: vcpkg share/openssl/copyright" },
  { name: "zlib", url: "https://zlib.net", license: "Zlib", copyright: "© 1995–2026 Jean-loup Gailly and Mark Adler", use: "Decompression throughout", usedBy: ["xpcog"], group: "interface", source: "XPCog: vcpkg share/zlib/copyright" },
  { name: "Brotli", url: "https://github.com/google/brotli", license: "MIT", copyright: "© 2009, 2010, 2013–2016 the Brotli Authors", use: "Compresses the remote control's HTTP responses", usedBy: ["xpcog"], group: "interface", source: "XPCog: /usr/share/licenses/brotli/LICENSE" },
  { name: "nlohmann/json", url: "https://github.com/nlohmann/json", license: "MIT", copyright: "© 2013–2025 Niels Lohmann", use: "Reads web services' replies", usedBy: ["xpcog"], group: "interface", source: "XPCog: /usr/share/licenses/nlohmann-json" },
  { name: "cpp-httplib", url: "https://github.com/yhirose/cpp-httplib", license: "MIT", copyright: "© 2017 yhirose", use: "Serves XPCog's remote control", usedBy: ["xpcog"], group: "interface", source: "XPCog: /usr/share/licenses/cpp-httplib" },
  { name: "Swagger UI", url: "https://github.com/swagger-api/swagger-ui", license: "Apache-2.0", use: "Shows the remote control's API documentation", usedBy: ["xpcog"], group: "interface", source: "XPCog: assets/swagger-ui/MANIFEST (5.29.1)" },
  { name: "sentry-native", url: "https://github.com/getsentry/sentry-native", license: "MIT", copyright: "© 2019 Sentry and individual contributors", use: "Opt-in crash reporting", usedBy: ["xpcog"], group: "interface", source: "XPCog: vcpkg share/sentry-native/copyright" },
  { name: "Crashpad", url: "https://chromium.googlesource.com/crashpad/crashpad", license: "Apache-2.0", use: "Catches crashes for sentry-native", usedBy: ["xpcog"], group: "interface", source: "XPCog: upstream (getsentry/crashpad) LICENSE" },
  { name: "libunwind", url: "https://www.nongnu.org/libunwind/", license: "MIT", copyright: "© 2002 Hewlett-Packard Co.", use: "Stack traces in crash reports on Linux", usedBy: ["xpcog"], group: "interface", source: "XPCog: /usr/share/licenses/libunwind/COPYING" },
  { name: "MASShortcut", url: "https://github.com/shpakovski/MASShortcut", license: "BSD-2-Clause", copyright: "© Vadim Shpakovski", use: "Global keyboard shortcuts", usedBy: ["cog"], group: "interface", source: "Cog: Frameworks/shpakovski/MASShortcut/LICENSE" },
  { name: "json-parser and json-builder", url: "https://github.com/json-parser/json-parser", license: "BSD-2-Clause", copyright: "© James McLaughlin", use: "Reads and writes JSON", usedBy: ["cog"], group: "interface", source: "Cog: ThirdParty/json/json.c, json-builder.c" },
  { name: "OpenURLPanel", url: "", license: "Apple sample code licence", copyright: "© 2004–2005 Apple Computer, Inc.", use: "The Open URL dialog", usedBy: ["cog"], group: "interface", source: "Cog: ThirdParty/OpenURLPanel/OpenURLPanel.m" },
  { name: "libavif", url: "https://github.com/AOMediaCodec/libavif", license: "BSD-2-Clause", copyright: "© Joe Drago", use: "Decodes AVIF cover art", usedBy: ["cog"], group: "interface", source: "Cog: ThirdParty/avif/include/avif/avif.h" },
  { name: "dav1d", url: "https://code.videolan.org/videolan/dav1d", license: "unknown", use: "Decodes AV1 for libavif", usedBy: ["cog"], group: "interface", source: "Cog: in ThirdParty/libraries.tar.xz; no licence in tree" },
  { name: "libyuv", url: "https://chromium.googlesource.com/libyuv/libyuv", license: "unknown", use: "Converts colours for libavif", usedBy: ["cog"], group: "interface", source: "Cog: in ThirdParty/libraries.tar.xz; no licence in tree" },
  { name: "AVIFQuickLook decoder", url: "https://github.com/dreampiggy/AVIFQuickLook", license: "unknown", use: "Decodes AVIF cover art", usedBy: ["cog"], group: "interface", source: "Cog: ThirdParty/avif/source/AVIFDecoder.m says '© 2019 dreampiggy', no terms" },
  { name: "ImageTextCell", url: "", license: "unknown", use: "Table cells with an icon", usedBy: ["cog"], group: "interface", source: "Cog: ThirdParty/ImageTextCell/ImageTextCell.h says '© 2001–2002 Apple. All rights reserved', no terms" },
  { name: "RetroArch Metal shaders", url: "https://www.retroarch.com", license: "GPL-3.0-or-later", copyright: "© Stuart Carnie, Daniel De Matteis", use: "Visualisation shaders", usedBy: ["cog"], group: "interface", source: "Cog: Visualization/ThirdParty/RetroArch/Shaders.metal" },
  { name: "DeaDBeeF spectrum analyser", url: "https://deadbeef.sourceforge.io", license: "Zlib", copyright: "© Alexey Yakovenko", use: "The spectrum analyser", usedBy: ["cog"], group: "interface", source: "Cog: Visualization/ThirdParty/deadbeef/analyzer.c" },
  { name: "SFBAudioEngine seconds formatter", url: "https://github.com/sbooth/SFBAudioEngine", license: "GPL-2.0-or-later", copyright: "© Stephen F. Booth", use: "Formats times", usedBy: ["cog"], group: "interface", source: "Cog: Formatters/SecondsFormatter.m" },
  { name: "swiftui-introspect", url: "https://github.com/siteline/swiftui-introspect", license: "MIT", copyright: "© 2019 Timber Software", use: "SwiftUI introspection", usedBy: ["cog"], group: "interface", source: "swiftui-introspect: upstream LICENSE at main, cloned 2026-10-01 (Swift package fetched at build)" },
  { name: "sentry-cocoa", url: "https://github.com/getsentry/sentry-cocoa", license: "MIT", copyright: "© 2015 Sentry", use: "Crash reporting", usedBy: ["cog"], group: "interface", source: "sentry-cocoa: LICENSE.md at main, cloned 2026-10-01" },
  { name: "MCP Swift SDK", url: "https://github.com/modelcontextprotocol/swift-sdk", license: "Apache-2.0 AND MIT", use: "The CogMCP server", usedBy: ["cog"], group: "interface", source: "swift-sdk: LICENSE at main, cloned 2026-10-01; mid-transition from MIT to Apache-2.0, code from contributors who have not relicensed stays MIT" },
  { name: "SwiftNIO", url: "https://github.com/apple/swift-nio", license: "Apache-2.0", copyright: "© 2017, 2018 The SwiftNIO Project", use: "Networking for CogMCP", usedBy: ["cog"], group: "interface", source: "swift-nio: LICENSE.txt and NOTICE.txt at main, cloned 2026-10-01" },
  { name: "swift-log", url: "https://github.com/apple/swift-log", license: "Apache-2.0", copyright: "© 2018, 2019 The SwiftLog Project", use: "Logging", usedBy: ["cog"], group: "interface", source: "swift-log: LICENSE.txt and NOTICE.txt at main, cloned 2026-10-01" },
  { name: "Logging.h", url: "", license: "unknown", use: "Debug logging macros", usedBy: ["cog"], group: "interface", source: "Cog: Utils/Logging.h ('Shamelessly stolen from stackoverflow', Dmitry Promsky), no licence" },

  // -------------------------------------------------------------------- data
  { name: "GeneralUser GS", url: "https://www.schristiancollins.com/generaluser.php", license: "GeneralUser GS License v2.0", copyright: "© 1997–2025 S. Christian Collins", use: "The bundled General MIDI SoundFont", usedBy: ["cog", "xpcog"], group: "data", source: "Cog: GeneralUserGS.sf3 INFO chunk; XPCog: docs/MIDI.md" },
  { name: "GeneralUser XG (SFe test)", url: "https://github.com/SFe-Team-was-taken/SFe", license: "GeneralUser GS License v2.0", copyright: "© 2025–2026 SFe Team and contributors; portions © 1997–2026 S. Christian Collins", use: "The bundled XG SoundFont", usedBy: ["cog", "xpcog"], group: "data", source: "GeneralUserXG-SFeTest.sf3 INFO chunk" },
  { name: "AdPlug database", url: "https://github.com/adplug/database", license: "public domain", use: "Per-song playback fixes for AdPlug", usedBy: ["cog", "xpcog"], group: "data", source: "Cog: Frameworks/AdPlug/AdPlug/database/README" },
  { name: "TG300B patch map", url: "https://github.com/spessasus/spessasynth_core", license: "unknown", use: "Maps TG300B patches to XG for the SFe bank", usedBy: ["cog", "xpcog"], group: "data", source: "tg300b.sflist.json, generated by spessasynth_core's docs/generators; no licence stated" },
  { name: "PlayStation 2 BIOS sound modules", url: "", license: "unknown", copyright: "Sony", use: "Runs PSF and PSF2 rips under HighlyExperimental", usedBy: ["cog", "xpcog"], group: "data", source: "hebios.bin; HighlyExperimental's Readme describes it as a stripped PS2 BIOS" },
  { name: "Commodore 64 ROMs", url: "", license: "unknown", copyright: "Commodore", use: "KERNAL, BASIC and character ROMs for SID playback", usedBy: ["cog", "xpcog"], group: "data", source: "Cog: Plugins/sidplay/roms.cpp; XPCog: codecs/sid/C64Roms.hpp" },
  { name: "Organya wavetable and PixTone sounds", url: "", license: "unknown", copyright: "Pixel (Daisuke Amaya)", use: "Instruments and drums for Organya music", usedBy: ["cog", "xpcog"], group: "data", source: "Cog: Plugins/Organya/wavetable.dat, fx96–fx9b.pxt; no licence" },
  { name: "YRW801 sample ROM", url: "", license: "unknown", copyright: "Yamaha", use: "The OPL4 wavetable, under libvgm", usedBy: ["xpcog"], group: "data", source: "XPCog: codecs/libvgm/Yrw801Rom.cpp; docs/PORTING.md lists it as an open question" },
  { name: "SADIE II HRTF (D02)", url: "https://www.york.ac.uk/sadie-project/", license: "unknown", use: "Headphone impulse responses for HRTF", usedBy: ["cog"], group: "data", source: "Cog: SADIE_D02-96000.mhr; no licence in tree" },
];
